### ISSUE TITLE
Support scoped packages

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/types-publisher#155]
`@types` can not support scoped packages. this will require:
- figuring out how they should be defined on DefinitelyTyped
- How they would be published
- changes to the ts compiler to find them

**Comment by Codesleuth** [comment]
I'd really like to publish typings for `@slack/client` but I see now way of doing it with the types publisher.
Has anyone made any headway towards thinking about this?

Is it possible to have a package URL such as this: `npmjs.com/package/@types/@slack/client`?

If not, could we possibly bundle definitions under a common package, so the package could be `npmjs.com/package/@types/@slack` with package files that match the scoped package e.g. `client.d.ts`?

**Comment by mhegazy** [comment]
I do not think npm supports nested scopes. one option is we can publish to `@types/_slack`, then use the `_` to mean `@` later on in the compiler when it is resolving the import.

**Comment by blakeembrey** [comment]
@mhegazy Would that mean tossing every definition into the same NPM package and losing versioning as a result? I don't think there's a way to achieve everything without changes to NPM at this point.

**Comment by mhegazy** [comment]
> Would that mean tossing every definition into the same NPM package and losing versioning as a result?

not sure i understand the question, can you elaborate?

**Comment by blakeembrey** [comment]
You suggested putting it under `_slack` (the module name in this example is `@slack/client` -> `@types/_slack`). Is that implying that you would put `/client` under the `@types/_slack` module, and if you do, doesn't that mean you can not version this module properly because it's a giant mix of everything under `@slack` now?

**Comment by Codesleuth** [comment]
You're right, that's a bad suggestion; sorry. I think it's unrealistic to expect a change to NPM to support this, and I think using an underscore is probably going to cause further problems in the future.

I don't have a better suggestion for now though... other than to prefix with something _unlikely_ to be chosen for a package name.

**Comment by mhegazy** [comment]
Well i was actually thinking of multiple packages.. something like `_slack_client` or `$slack$client`.. some sort of serialization...

**Comment by blakeembrey** [comment]
Right, but now it'll be difficult for people to install and you can end up with conflicts because the current packages don't serialise in any way - unless they get made consistent with whatever approach you use. That's what I was looking at doing for Typings, but I figured it was reasonable for Typings since a separate tool was doing those mappings - in this case a human needs to do them and do them consistently. It might not be bad if there's an obvious way it'd work.

**Comment by Codesleuth** [comment]
Perhaps it's time to open up discussions with NPM? Maybe they have something in the pipeline that will enable support for nested scopes.

**Comment by andy-ms** [comment]
@mhegazy Can we commit to using `@types/foo__bar` to represent `@foo/bar`? Would like to start using it on DefinitelyTyped even if we don't have compiler support yet.
(Useful: https://github.com/npm/validate-npm-package-name)

**Comment by amcasey** [comment]
@andy-ms Can this be closed?
