### ISSUE TITLE
How to force newer version

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/types-publisher#168]
When installing react via `npm i --save-dev @types/react` it installs historic 0.14.x version of typings. Yet, definitely typed as well as npm has typings for new version 15.0. How can I force typings to grab this version? Thanks!

**Comment by johnnyreilly** [comment]
I believe that these Typings are one and the same... API wise the bump from 0.14 to 15.0 is no different (I think). So the Typings are labeled 0.14 as they are in Definitely Typed. See: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts

**Comment by tomitrescak** [comment]
They are different typing a as one is more focused on generics than the other. But the problem is more generic. How do I select a specific version in general,? It's doable with typings

**Comment by mhegazy** [comment]
The package on npm comes from DT, so here is the latest: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react/index.d.ts

Every time this file is updated a new package will be published.

the version of the npm package comes from the header of the file. currently it says `0.14`, changing it to `15` will result in publishing a new version.

@tomitrescak does this answer your question?

**Comment by tomitrescak** [comment]
Well, I was more trying to understand how can I use different versions of typings. If I have two different versions of the same package in my project that have different typings, how can it be solved?

**Comment by mhegazy** [comment]
you can have different `node_modules` at different levels:

```tree
node_modules
| --- @types
|         | --- shared-module
| --- ProjectA
|         | --- node_modules
|         |         | --- @types
|         |         |         | --- project-specific-module@1.0
| --- ProjectB
|         | --- node_modules
|         |         | --- @types
|         |         |        | --- project-specific-module@2.0

```

**Comment by tomitrescak** [comment]
@mhegazy thanks for the explanation, it makes a lot of sense. But what about a situation that package will bring incompatible dependencies into project? 

I have a package that desires "/// <reference types="es6-shim" />" in my project which is targeting es6. I cannot import @types/es6-shim as it results in duplicates. Specifying `types: []` in my tsconfig.json does not do anything in this case.

**Comment by mhegazy** [comment]
Either you too depend on the shims definition file, and in this case, do not include the library for ES6, i.e. `--lib es5,dom` or that it is not needed, then the declaration file should not take a dependency on the shims.

The later would seem to be the more reasonable approach, since something like `Promise` is known to point to ES6 Promise, and having it from es6-shims or the default library is an implementation detail, and should not entail a dependency between the two packages.

you can override your @types packages if you need to. though this would not be the recommendation. 

I believe this is already reported/discussed in https://github.com/Microsoft/TypeScript/issues/11671#issuecomment-254329003. I am still working my way through the thread :)

**Comment by tomitrescak** [comment]
Ok, thanks @mhegazy, I'll wait what will pop up from the other thread ;)

the problem is that I DO NOT depend on es6-shim and it is pulled to project by that dependency from the package. I'll close this one.
