### ISSUE TITLE
webrtc typings are not properly converted

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/types-publisher#181]
Hello, I was told to post here. http://stackoverflow.com/q/40441252/2715716

I am trying to use `webrtc` typing by installing `npm i @types/webrtc --save-dev` and using `"moduleResolution": "node"`. However with `webrtc` typings it doesn't work. Maybe this is a bug in the publisher process?

**Comment by MeirionHughes** [comment]
>app.ts(2,25): error TS2306: File 'C:/Users/.../src/node_modules/@types/webrtc/index.
d.ts' is not a module.

contents of index.d.ts: 
```
// Type definitions for webrtc
// Project: https://webrtc.org/
// Definitions by: Toshiya Nakakura <https://github.com/nakakura>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference path="RTCPeerConnection.d.ts" />
/// <reference path="MediaStream.d.ts" />
```

both of those referenced files are present.

**Comment by TomasHubelbauer** [comment]
Yes they are, but please see the question. When I use `moduleResolution` `node` and `import * as webrtc from "webrtc"` it says the error. I have to use `/// <reference …` instead. Should I be able to not do that? Or is that only the case when importing an actual package with code and not just typings - the typings are pulled based on a name of the actual package which I am importing? Because I tried that, too in the question but it still didn't help.

I do not mean to abuse this issue tracker by asking TypeScript noob questions so let me reduce it to this: is using `reference` correct in this case and the only solution? The typings are alright?

**Comment by MeirionHughes** [comment]
Sorry, I was wrong... the typings are fine I think.

**Comment by andy-ms** [comment]
When you write `import * as webrtc from "webrtc";`, this is an ES6 construct that will be part of the compiled JavaScript code. (Or at least a CommonJS/AMD equivalent will depending on settings.) However, there is no importable `webrtc` at runtime, and the type declarations reflect this by declaring globals rather than a module. So, the compiler produces an error.

`<reference types="webrtc" />` is different because this is *not* an ES6 construct; it is TypeScript-specific and has no runtime component. So all it does is bring the file at `node_modules/@types/webrtc/index.d.ts` into the project to make its declarations available.

**Comment by MeirionHughes** [comment]
yeah this should be closed. `import "webrtc"` brings in the typings without actually importing anything

**Comment by andy-ms** [comment]
OK. Note that `import "webrtc"` transpiles to `require("webrtc");` while `/// <reference types="webrtc" />` transpiles to a comment, so it matters which one you use.
