### ISSUE TITLE
Mention where to log issues in README.md

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/types-publisher#36]
README.md should list https://github.com/Microsoft/TypeScript as the place to log issues if a type definition is being published incorrectly

**Comment by RyanCavanaugh** [comment]
Clarification: The generated readme.md file we publish, not the local repo's readme

**Comment by mhegazy** [comment]
There are different set of issues, and i am not sure where should these be logged...

1. there are definition issues, accuracy, noImplcitAny, strictNullChecks, etc.. these are caused by declaration file content, which lives on DT.
2. publish issues, like version mismatch, invalid dependency, package names, etc..
3. language issues, like conflicting declaration issues, can not merge types in certain context, how a file should be authored, or uses, etc..


I believe 2, and 3 are the minority, the majority of issues fall in 1. so the link should be to definitely typed instead.

**Comment by RyanCavanaugh** [comment]
Good point, I agree.
