### ISSUE TITLE
Unable to import  _spPageContextInfo

### ISSUE THREAD

**Issue by vinod2589** [Microsoft/types-publisher#363]
Hello everyone,
I am trying to import the _spPageContextInfo class from my node_modules using the following import statement/syntax in my .ts file in an spfx solution.

import {
_spPageContextInfo
} from '@types/sharepoint';

I am unable to import the class as i need it to get the absolute url of the page in my webpart.
Also the types-metadata.json file is missing inside @types/sharepoint folder.

I hope i am raising this issue at the right place.
@baywet

**Comment by baywet** [comment]
You should not need to import this one as it's declared as a global variable.
Just make sure your tsconfig.json includes that in the compilerOptions `"typeRoots": [ "node_modules/@types/" ],`

**Comment by andy-ms** [comment]
TypeScript should be picking up on `@types` dependencies automatically already. You could add `/// <reference types="libraryname" />` to the code to make sure, and use `--traceResolution` to see where the compiler is looking for it.
`types-metadata.json` isn't needed, so don't worry about that.

**Comment by vinod2589** [comment]
Thanks for your quick responses,
I added the typeRoots as Vincent mentioned in my tsconfig.json file, 

![tsconfig](https://user-images.githubusercontent.com/30411015/28564551-f2ccddbc-7146-11e7-992e-dbea28692ef7.png)

And when I come back to my Webpart.ts file and type _spPageContextInfo it still gives me the error, not sure where this is going wrong.

**Comment by baywet** [comment]
From what I can see you're working on a SharePoint framework project.
I get the type declarations to be recognized by having this tsconfig file (I created a dummy SPFX project to test it out).
One (or many) of the differences in the config file is what prevents it from working properly, however I'm not sure of which one at the moment.
Also you should consider something when working on SPFX, the global variables provided by SharePoint (_spPageContextInfo for instance) are not guaranteed to be here on modern pages. So you probably should not rely on that. (you can have a look at [that tweeter discussion](https://twitter.com/PatMill_MSFT/status/876948133191614464) I had with some engineers a couple of months ago)
You should use `.legacyPageContext` instead (which doesn't rely on these types because, oh well they decided so)
I hope that answers your question.
```
{
  "compilerOptions": {
    "target": "ES5",
    "lib": [
      "dom",
      "dom.iterable",
      "es2015",
      "scripthost"
    ],
    "sourceMap": true,
    "typeRoots": [ "node_modules/@types/" ],
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "declaration": false,
    "watch": true,
    "strict": false
  },
  "compileOnSave": true,
  "include": [
    "src/**/*"
  ],
  "exclude": [
    ".vscode",
    "node_modules",
    "dist"
  ]
}
```

**Comment by baywet** [comment]
BTW the issue should probably have been opened at https://github.com/DefinitelyTyped/DefinitelyTyped/ instead :)

**Comment by vinod2589** [comment]
Yes, you are right I am working on a spfx framework solution and previously I was trying to use this.context.pageContext.web.absoluteUrl which doesn't works in the beginning of the Render() event. But I tried what you suggested and it works like a charm i.e. this.context.pageContext.legacyPageContext.webAbsoluteUrl. Thanks for your quick response. I would appreciate if you can tell me how to decide where/which repository an issue is supposed to be raised, as I am new to GitHub but I'm very sure that I will be very much active from now on. Closing this issue. Cheers :-)
