### ISSUE TITLE
Be smarter about republishes

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/types-publisher#5]
Right now we pessimistically assume that all past NPM publishes may have failed and query the NPM DB every time. This is slow and hinders fast incremental publish.

We should have two targets: incremental publish, and full publish. Incremental should assume that only 'new' versions need publishing, and full publish should do the full querying and republishing.

Also, only a full publish should fetch NPM package download counts.

**Comment by andy-ms** [comment]
This is mostly fixed by #132. The webhook will only ever publish changed packages. A full publish must be done by hand.
Indexing is a separate step from publishing, and currently indexes every package regardless of whether it's changed. Fetching the NPM download counts for everything seems to be fast enough, though.

**Comment by andy-ms** [comment]
I think `calculate-versions` is fast enough that we don't have to be any smarter.
